kind: Service
apiVersion: v1
metadata:
  name: influxdb-svc
  namespace: uniris-metrics
  labels:
    project: uniris
spec:
  selector:
    app: influxdb
  type: NodePort
  ports:
    - name: http-grafana
      protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 31003
    - name: tcp-influx
      protocol: TCP
      port: 8086
      targetPort: 8086
      nodePort: 31086
    - name: udp-statsd
      protocol: UDP
      port: 8125
      targetPort: 8125
      nodePort: 31125
    - name: http-influx-admin
      protocol: TCP
      port: 8888
      targetPort: 8888
      nodePort: 31888

---
