apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentbit-cm-v7
  namespace: uniris-metrics
  labels:
    project: uniris
data:
  fluent-bit.conf: |-
    [SERVICE]
      Flush          1
      Daemon         Off
      Log_Level      info
      Parsers_File   parsers.conf
      HTTP_Server    On
      HTTP_Listen    0.0.0.0
      HTTP_Port      2020

    [INPUT]
      Name        tcp
      Listen      0.0.0.0
      Port        5170
      Chunk_Size  32
      Buffer_Size 64
      Format      json

    [OUTPUT]
      Name  stdout
      Match *